import unittest
from unittest.mock import MagicMock, patch, ANY
import io
from pathlib import Path
from core.services.generation_service import GenerationService

class TestGenerationService(unittest.TestCase):
    def setUp(self):
        self.api_key = "test_key"
        self.service = GenerationService(self.api_key)

    @patch('core.services.generation_service.genai.Client')
    def test_init(self, mock_client_cls):
        service = GenerationService("key")
        self.assertIsNotNone(service.client)
        mock_client_cls.assert_called_with(api_key="key")

    @patch('core.services.generation_service.Image.open')
    def test_generate_image_api_call(self, mock_img_open):
        # Setup Mock Image
        mock_img = MagicMock()
        mock_img.size = (1024, 1024)
        mock_img.format = "PNG"
        # Mock context manager for Image.open
        mock_img_open.return_value.__enter__.return_value = mock_img
        
        # Mock Client
        self.service.client = MagicMock()
        mock_response = MagicMock()
        mock_part = MagicMock()
        # Mock inline data for result image
        mock_part.inline_data.data = b"fake_image_bytes"
        mock_response.parts = [mock_part]
        self.service.client.models.generate_content.return_value = mock_response

        # Mock _save_generated_image to avoid actual disk IO in this specific test
        # (We will test _save separately or rely on mocking Path/Image in integration)
        with patch.object(self.service, '_save_generated_image') as mock_save:
            mock_save.return_value = {'success': True}
            
            prompt_data = {'prompt': 'A cat', 'title': 'Cat'}
            out_config = {'resolution': '1K', 'ratio': '1:1', 'project_out_dir': Path('/tmp')}
            
            result = self.service.generate_image(prompt_data, Path("dummy.png"), out_config)
            
            # Verify API called
            self.service.client.models.generate_content.assert_called_once()
            
            # Verify Save called
            mock_save.assert_called_once()

    @patch('core.services.generation_service.Image.open')
    @patch('pathlib.Path.mkdir') # prevent directory creation
    def test_save_structure_logic(self, mock_mkdir, mock_img_open):
        """Test the logic of filename construction and save path."""
        # Setup Mock generated image
        mock_gen_img = MagicMock()
        mock_gen_img.size = (1024, 1024)
        
        # Setup Mock source image (same size -> no diff)
        mock_src_img = MagicMock()
        mock_src_img_ctx = MagicMock()
        mock_src_img_ctx.size = (1024, 1024)
        
        # Image.open is called twice: once for source (in main), once for generated (in save)
        # We need to control return values.
        # However, _save_generated_image only opens the generated bytes.
        # The main generate_image opens source.
        # Let's test _save_generated_image directly to isolate logic.
        
        mock_img_open.return_value = mock_gen_img # simplify for direct call
        
        prompt_data = {'prompt': 'A cat', 'title': 'Cat'}
        source_path = Path("C:/Source/input.png")
        config = {'project_out_dir': Path("C:/Out"), 'format': 'PNG'}
        input_size = (1024, 1024)
        
        # Mock save
        mock_gen_img.save = MagicMock()
        
        result = self.service._save_generated_image(b"data", prompt_data, source_path, config, input_size)
        
        self.assertTrue(result['success'])
        saved_path = result['saved_path']
        
        # Check folder structure: Project / Stem / Filename
        # Stem of input.png is input
        expected_folder = Path("C:/Out/input")
        self.assertIn(str(expected_folder), str(saved_path))
        
        # Check filename contains title
        self.assertIn("Cat", saved_path.name)
        
        # Check extension
        self.assertTrue(str(saved_path).endswith(".png"))
        
        # Verify save called
        mock_gen_img.save.assert_called_once()

